### ISSUE TITLE
Hard to cancel when there is no loadshedding

### ISSUE THREAD

**Issue by m3h** [m3h/loadshedding#1]
If there is power to the PC, but the schedule and loadshedding status indicates that there shouldn't be, your PC will powerdown/hibernate as soon as you switch it on.

A temporary fix is to disable the internet (and therefore the checking of the loadshedding status) before starting up the PC.

**Comment by m3h** [comment]
I think a more ideal fix, would be for the script to only 'run-once' per loadshedding block.

E.g. if the script runs, and the PC is due for loadshedding soon, it should try and execute the action - the most logical being to power-off.
If the PC then is switched on during loadshedding, the script should have remembered that it already executed the action during this current block, and not perform the action again

**Comment by m3h** [comment]
[test.drawio.pdf](https://github.com/m3h/loadshedding/files/7420763/test.drawio.pdf)
![test drawio](https://user-images.githubusercontent.com/18686801/138942575-ed01e3f4-4f33-43b6-928a-c892d9384973.png)

This is what I'm thinking in terms of a working flow.
This won't really handle cases where the stage drops intermittently (and probably other edge cases), but it should work fine most of the time.

**Comment by m3h** [comment]
@knoffelcut, would this mitigate the issue you're facing with CoT schedule differences?

**Comment by knoffelcut** [comment]
Yes, this should be a good temporary fix for the CoT schedule differences as well as the odd occasions where loadshedding is scheduled to happen but doesn't.

Regarding the flow diagram, I believe it is mostly correct. The only significant changes I would make is:
- Add a timestamp to the RAN flag
- Only clear the previous RAN flag when the area is scheduled for loadshedding. The information captured in the RAN flag is only relevant when an area is actually scheduled for loadshedding, and this approach minimizes HDD reads and writes.

"This won't really handle cases where the stage drops intermittently (and probably other edge cases), but it should work fine most of the time." - I agree. I believe the two issues this addresses (CoT schedules and odd occasions) happens more frequently than intermittent stage changes within a block, so it is the lesser of two evils.

**Comment by m3h** [comment]
> Only clear the previous RAN flag when the area is scheduled for loadshedding.
Wouldn't that result in
1. loadshedding is scheduled
2. script runs, sets RAN flag (with timestamp), and performs action
3. No loadshedding occurs, the script clears the RAN flag
4. Repeat from 1?

Whereas with the flow diagram that I posted, wouldn't you have
1. loadshedding is scheduled
2. scripts runs, sets RAN flag, and performs action
3. No loadshedding occurs, the script sees the RAN flag so skips action
4. The loadshedding block ends, the script runs and clears the RAN flag

**Comment by knoffelcut** [comment]
Not exactly. See the attached diagram for my proposed solution. Rather than think of it as a RAN flag, it is more like a RAN timestamp, that simply stores the last time the area was in loadshedding.
[loadshedding_issue_1_proposed_solution.drawio.pdf](https://github.com/m3h/loadshedding/files/7446776/loadshedding_issue_1_proposed_solution.drawio.pdf)

**Comment by knoffelcut** [comment]
As discussed in the commit message, I rather followed the proposed solution at https://github.com/m3h/loadshedding/issues/1#issuecomment-952217448

I have implemented the feature (branch `feature-#1`), and all branches of the flow chart was manually tested. However, I would rather wait for the next bunch of loadshedding before opening a pull request.

**Comment by m3h** [comment]
Your wish for loadshedding has been granted. We're scheduled for stage 4 at 4 PM today.

**Comment by m3h** [comment]
Would you like to open a PR for this?

**Comment by knoffelcut** [comment]
I'm actually testing this right now, my electricity is supposed to be off, but if isn't. Will open PR if it works

Edit: Nope, electricity is off. Was blessed for a few minutes
