### ISSUE TITLE
Move configuration out of `loadshedding.py`

### ISSUE THREAD

**Issue by knoffelcut** [m3h/loadshedding#2]
Currently the user configuration is inside the primary code file, `loadshedding.py`. This hinders collaboration on the code between developers in different regions.

This feature should move all user configuration out of the primary code files, either in some standard format like JSON or YAML files, or simply in Python configuration files.

The code snippets below show some of the parameters that will be moved to user configuration files:
```
AREA='8B'
MIN_OFFSET = 4 # minutes
MAX_OFFSET = 17 # minutes

NOTIFICATION_TIMEOUT = 120
CMD = "sudo /usr/sbin/s2disk"
```
and
```
SCHEDULE_CSV = '/home/reece/scripts/loadshedding/load_shedding_cp.csv'
```

The snippets below can potentially be moved to application configuration files:
```
API_URL = "http://loadshedding.eskom.co.za/LoadShedding/GetStatus"
```
and
```
LOGSTAGE = "/home/reece/scripts/loadshedding/stagelog.txt"
LOG = "/home/reece/scripts/loadshedding/log.log"
```

**Comment by m3h** [comment]
Yeah, that's a good point.
I might have a look at adding that, but PRs are welcome.

There are some bigger issues (like the Gtk dependency, and the API endpoint being unreliable); but maybe making the code more attractive will garner enough interest to get those issues fixed...
